from os import PathLike
from typing import Sequence

_Path = str | PathLike[str]

class Engine:
    @staticmethod
    def load(path: _Path) -> Engine: ...
    @staticmethod
    def from_edges(input_edges: _Path, plastic_edges: _Path, *, actions: int = 2,
                   learning_rate: float = 0.02, logit_gain: float = 6.0,
                   active_fraction: float = 0.1, weight_limit: float = 1.0,
                   homeostasis: bool = True, readout: str = 'positive') -> Engine: ...
    @property
    def input_ids(self) -> list[int]: ...
    @property
    def hidden_ids(self) -> list[int]: ...
    @property
    def output_ids(self) -> list[int]: ...
    @property
    def output_actions(self) -> list[int]: ...
    @property
    def output_gains(self) -> list[float]: ...
    @property
    def weights(self) -> list[float]: ...
    @property
    def config(self) -> dict[str, int | float | bool]: ...
    def infer(self, rates: Sequence[float]) -> list[float]: ...
    def infer_batch(self, rows: Sequence[Sequence[float]]) -> list[list[float]]: ...
    def learn(self, rows: Sequence[Sequence[float]], actions: Sequence[int], rewards: Sequence[float]) -> None: ...
    def set_output_actions(self, actions: Sequence[int]) -> None: ...
    def set_output_gains(self, gains: Sequence[float]) -> None: ...
    def save(self, path: _Path, *, overwrite: bool = False) -> None: ...
