"""Real FunctionGemma generation -> HTTP tool call -> real novi -> host feedback."""
import argparse,http.client,json,threading,time
from pathlib import Path
import secrets
import torch
from transformers import AutoTokenizer,AutoModelForCausalLM
from protocol import tools,parse,Session
from runtime import NoviBackend
from server import make_server
from evaluate import BASE

p=argparse.ArgumentParser();p.add_argument('--adapter',type=Path);p.add_argument('--function-model',default='/Users/a405394/models/google_functiongemma-270m-it');p.add_argument('--embedding-model',default='/Users/a405394/models/google_embeddinggemma-300m');p.add_argument('--out',type=Path,default=Path('results/function-bridge/live.json'));a=p.parse_args()
tok=AutoTokenizer.from_pretrained(a.function_model,local_files_only=True)
model=AutoModelForCausalLM.from_pretrained(a.function_model,local_files_only=True,dtype=torch.bfloat16).to('mps').eval()
if a.adapter:
 from peft import PeftModel
 model=PeftModel.from_pretrained(model,str(a.adapter)).eval()
backend=NoviBackend(a.embedding_model,'results/gemma-bridge');s=Session(backend.decide)
# Runtime-only random capability is never declared to or generated by the model.
capability=secrets.token_urlsafe(32)
server=make_server(s,feedback=backend.learn,environment_token=capability)
thread=threading.Thread(target=server.serve_forever,daemon=True);thread.start()
client=http.client.HTTPConnection('127.0.0.1',server.server_port,timeout=20)
records=[]
def post(path,payload,trusted=False):
 headers={'Content-Type':'application/json'}
 if trusted:headers['Authorization']='Bearer '+capability
 client.request('POST',path,json.dumps(payload),headers);r=client.getresponse();body=json.loads(r.read())
 if r.status!=200:raise RuntimeError(body)
 return body
try:
 for goal in ['water','food','warmth','rest']:
  episode=[]
  for prompt in [f'Set my goal to {goal}.','Choose an action using the neural policy.']:
   inputs=tok.apply_chat_template([{'role':'developer','content':BASE},{'role':'user','content':prompt}],tools=tools(),add_generation_prompt=True,return_dict=True,return_tensors='pt').to('mps')
   start=time.perf_counter()
   with torch.inference_mode():out=model.generate(**inputs,do_sample=False,max_new_tokens=80,pad_token_id=tok.pad_token_id)
   torch.mps.synchronize();raw=tok.decode(out[0,inputs['input_ids'].shape[1]:],skip_special_tokens=False)
   name,args=parse(raw);result=post('/v1/call',{'name':name,'arguments':args})
   episode.append({'prompt':prompt,'raw':raw,'result':result,'seconds':time.perf_counter()-start})
  # Toy environment knows the requested outcome; the language model cannot choose reward.
  action=episode[-1]['result'];reward=1 if action['meaning']==goal else -1
  post('/v1/environment/outcome',{'action_id':action['id'],'reward':reward},trusted=True)
  records.append({'requested_goal':goal,'steps':episode,'host_reward':reward})
  print(goal,action['meaning'],reward,flush=True)
 a.out.write_text(json.dumps({'adapter':str(a.adapter) if a.adapter else None,'scope':'four explicit goal requests, real model generation and loopback HTTP, host-computed bandit reward','episodes':records},ensure_ascii=False,indent=2)+'\n')
finally:client.close();server.shutdown();server.server_close();thread.join()
